config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  
  root                        'users#show'
  post    '/'             =>  'users#create'
  post    'changemyemail' =>  'users#new_email'
  post    'sendemail'     =>  'sessions#send_email'
  post    'unexpected'    =>  'goals#unexpected'
  post    'remove_session'=>  'sessions#remove'
  post    'login'         =>  'sessions#create'
  get     'help'          =>  'static_pages#help'
  get     'resend'        =>  'users#resend'
  get     'profile'       =>  'users#edit'
  get     'privacy'       =>  'static_pages#privacy'
  get     'terms'         =>  'static_pages#terms'
  patch   'profile'       =>  'users#edit'
  delete  'logout'        =>  'sessions#destroy'
  
  resources :contacts, :path => 'contact', only: [:index, :new, :create]
  resources :users,               only: :update
  resources :account_activations, only: :edit
  resources :sessions,            only: :edit
  resources :change_user_email,   only: :edit
  resources :interactions,        only: [:index, :show, :update]
  resources :subscriptions,       :path => 'tracks', only: [:index, :update]
  resources :posts, :path => 'blog', only: [:index, :show]
  
  resources :improvements, :path => 'haves'
  
  resources :accomplishments, :path => 'crucendos'
  
  namespace :accomplishments do
    resources :crucendos
  end
  
  resources :goals, :path => 'wants' do
    post 'improve', on: :member
  end
  
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :questions do
      post :import, on: :collection
    end
    resources :topics, :path => 'tracks' do
      post :activate_questions, on: :member
    end
    resources :authors
    resources :users
    resources :skills
    resources :posts
  end
  

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :logged_in_user
  
  # Prevent flash from appearing twice after AJAX call
  after_filter { flash.discard if request.xhr? }
  
  def index
    @subscriptions = Topic.active(true).order(name: :asc)
  end
  
  def update
    @topic = Topic.find(params[:id])
    if current_user.subscribed?(@topic) 
      unless current_user.subscriptions.size < 6
        current_user.unsubscribe(@topic)
        # Successfully unsubscribed
        set_flash :unsubscribed, type: :success, object: @topic
      end
    else 
      current_user.subscribe(@topic)
      # Successfully subscribed
      set_flash :subscribed, type: :success, object: @topic
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_panel.html.erb
<div id="topic_<%= topic.id %>" class="col-lg-3 col-md-4 col-sm-6">
  <div class="panel panel-default subscription-panel 
    <%="subscribed" if current_user.subscribed?(topic) %>">
    <%= link_to subscription_path(topic), 
          method: :patch, remote: true, class: "update-subscription" do %>
      <div class="panel-heading">
        <h4 class="panel-title"><%= topic.name.camelize %></h4>
      </div>
    <% end %>
    <div class="panel-body">
      <% unless topic.author.blank? %>
      <div class="row">
        <div class="col-xs-6 col-sm-12">
          <%= image_tag topic.author.logo.url, class: "img-responsive" if topic.author.logo? %>
        </div>
        <div class="col-xs-6 col-sm-12">
          <h4><small>Brought to you by</small><br><%= link_to topic.author.name, topic.author.link, target: '_blank' %></h4>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/index.html.erb
<% title "Tracks" %>
<% provide(:navigation_heading, "Tracks") %>
<div class="subscriptions">
  <div class="row">
    <%= render partial: "subscriptions/panel", 
          collection: @subscriptions, as: 'topic' %>
  </div>
</div>
<div class="modal fade" id="subscription-limit" tabindex="-1" role="dialog" 
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content confirm-modal">
      <div class="modal-header">
        <button type="button" class="modal-button-right close-icon" 
          data-dismiss="modal" aria-hidden="true">
          <%= material_icon.done %>
        </button>
        <h4 class="modal-title">Tracks Limit</h4>
      </div>
      <div class="modal-body">
        <h3>You must be on at least five tracks!</h3>
        <p>This is so you get a good variety of questions in Crucendo.</p>
      </div>
    </div>
  </div>
</div>