config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  
  root                        'users#show'
  post    '/'             =>  'users#create'
  post    'changemyemail' =>  'users#new_email'
  post    'sendemail'     =>  'sessions#send_email'
  post    'unexpected'    =>  'goals#unexpected'
  post    'remove_session'=>  'sessions#remove'
  post    'login'         =>  'sessions#create'
  get     'help'          =>  'static_pages#help'
  get     'resend'        =>  'users#resend'
  get     'profile'       =>  'users#edit'
  get     'privacy'       =>  'static_pages#privacy'
  get     'terms'         =>  'static_pages#terms'
  patch   'profile'       =>  'users#edit'
  delete  'logout'        =>  'sessions#destroy'
  
  resources :contacts, :path => 'contact', only: [:index, :new, :create]
  resources :users,               only: :update
  resources :account_activations, only: :edit
  resources :sessions,            only: :edit
  resources :change_user_email,   only: :edit
  resources :interactions,        only: [:index, :show, :update]
  resources :subscriptions,       :path => 'tracks', only: [:index, :update]
  resources :posts, :path => 'blog', only: [:index, :show]
  
  resources :improvements, :path => 'haves'
  
  resources :accomplishments, :path => 'crucendos'
  
  namespace :accomplishments do
    resources :crucendos
  end
  
  resources :goals, :path => 'wants' do
    post 'improve', on: :member
  end
  
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :questions do
      post :import, on: :collection
    end
    resources :topics, :path => 'tracks' do
      post :activate_questions, on: :member
    end
    resources :authors
    resources :users
    resources :skills
    resources :posts
  end
  

end

app/models/remember.rb
class Remember < ActiveRecord::Base
  belongs_to :user

end

app/views/remembers/_remember.html.erb
<% current = current_session?(remember) %>
<div id="remember_<%= remember.id %>" class="panel panel-default remember">
  <div class="panel-body">
    <%= link_to 'End Session', remove_session_path(id: remember.id), 
          method: :post, remote: true, 
          class: "btn btn-red pull-right" unless current %>
    <span><%= remember.browser %>, <%= remember.platform %> 
    <%= '(current device)' if current %></span> 
    <span>Created <%= time_ago_in_words(remember.created_at) %> ago</span>
    <span>Last registered <%= time_ago_in_words(remember.updated_at) %> ago</span>
  </div>
</div>